from ai.graph.state import AgentState
from ai.tools.tool_registry import ALL_TOOLS


def tool_executor(state: AgentState) -> AgentState:
    """
    Executes the selected tool using parameters
    generated by the domain agent.
    """

    tool_name = state.get("tool_name")
    tool_input = state.get("tool_input") or {}

    if not tool_name:
        raise ValueError("Tool name missing in state.")

    if tool_name not in ALL_TOOLS:
        raise ValueError(f"Unknown tool: {tool_name}")

    tool_function = ALL_TOOLS[tool_name]

    try:
        result = tool_function(**tool_input)
    except Exception as exc:
        result = {
            "error": str(exc),
            "tool": tool_name,
        }

    state["tool_output"] = result

    return state